module.exports = {
  id: "nginx_502",
  title: "502 Bad Gateway — Production Down",
  difficulty: "standard",
  timeLimit: 900,
  brief: "Your monitoring alert fired 3 minutes ago: app.company.com returns 502 Bad Gateway. Users cannot access the application. Diagnose and fix the issue. You are logged in as the deploy user on the production server.",
  successCommand: "curl localhost",
  commandMap: {
    "curl localhost": "HTTP/1.1 502 Bad Gateway\nServer: nginx\nDate: [timestamp]\n\n<html><head><title>502 Bad Gateway</title></head><body><h1>502 Bad Gateway</h1><p>The server encountered a temporary error and could not complete your request.</p></body></html>",
    "curl -i localhost": "HTTP/1.1 502 Bad Gateway\nServer: nginx/1.18.0\nContent-Type: text/html",
    "curl -I localhost": "HTTP/1.1 502 Bad Gateway\nServer: nginx/1.18.0\nContent-Type: text/html",
    "curl localhost:3001": "curl: (7) Failed to connect to localhost port 3001: Connection refused",
    "systemctl status nginx": "● nginx.service - A high performance web server\n   Loaded: loaded (/lib/systemd/system/nginx.service; enabled)\n   Active: active (running) since Mon 2024-01-15 09:23:11 UTC; 2h 14min ago\n Main PID: 1234 (nginx)",
    "nginx -t": "nginx: the configuration file /etc/nginx/nginx.conf syntax is ok\nnginx: configuration file /etc/nginx/nginx.conf test is successful",
    "cat /etc/nginx/sites-enabled/app.conf": "upstream backend {\n    server 127.0.0.1:3001;\n}\n\nserver {\n    listen 80;\n    server_name app.company.com;\n\n    location / {\n        proxy_pass http://backend;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_connect_timeout 5s;\n        proxy_read_timeout 30s;\n    }\n}",
    "systemctl status app": "● app.service - Node.js Application Server\n   Loaded: loaded (/etc/systemd/system/app.service; enabled)\n   Active: failed (Result: exit-code) since Mon 2024-01-15 11:31:44 UTC; 6min ago\n  Process: 8821 ExecStart=/usr/bin/node /opt/app/server.js (code=exited, status=1/FAILURE)\n\nJan 15 11:31:44 prod-01 node[8821]: Error: MONGODB_URI environment variable is not set\nJan 15 11:31:44 prod-01 node[8821]:     at Object.<anonymous> (/opt/app/config/db.js:3:9)\nJan 15 11:31:44 prod-01 systemd[1]: app.service: Main process exited, code=exited, status=1/FAILURE",
    "journalctl -u app": "-- Logs begin at Mon 2024-01-15 09:00:00 UTC --\nJan 15 11:31:44 prod-01 node[8821]: Error: MONGODB_URI environment variable is not set\nJan 15 11:31:44 prod-01 node[8821]:     at Object.<anonymous> (/opt/app/config/db.js:3:9)\nJan 15 11:31:44 prod-01 node[8821]:     at Module._compile (node:internal/modules/cjs/loader:1356:14)\nJan 15 11:31:44 prod-01 systemd[1]: app.service: Main process exited, code=exited, status=1/FAILURE\nJan 15 11:31:44 prod-01 systemd[1]: app.service: Failed with result 'exit-code'.\nJan 15 11:31:44 prod-01 systemd[1]: Failed to start Node.js Application Server.",
    "journalctl -u app -n 20": "-- Logs begin at Mon 2024-01-15 09:00:00 UTC --\nJan 15 11:31:44 prod-01 node[8821]: Error: MONGODB_URI environment variable is not set\nJan 15 11:31:44 prod-01 node[8821]:     at Object.<anonymous> (/opt/app/config/db.js:3:9)\nJan 15 11:31:44 prod-01 systemd[1]: app.service: Failed with result 'exit-code'.",
    "journalctl -u app -n 50": "-- Logs begin at Mon 2024-01-15 09:00:00 UTC --\nJan 15 11:31:44 prod-01 node[8821]: Error: MONGODB_URI environment variable is not set\nJan 15 11:31:44 prod-01 node[8821]:     at Object.<anonymous> (/opt/app/config/db.js:3:9)\nJan 15 11:31:44 prod-01 systemd[1]: app.service: Failed with result 'exit-code'.",
    "cat /etc/systemd/system/app.service": "[Unit]\nDescription=Node.js Application Server\nAfter=network.target\n\n[Service]\nType=simple\nUser=app\nWorkingDirectory=/opt/app\nEnvironmentFile=/opt/app/.env\nExecStart=/usr/bin/node /opt/app/server.js\nRestart=on-failure\n\n[Install]\nWantedBy=multi-user.target",
    "ls /opt/app": "config/  logs/  node_modules/  package.json  server.js  .env.example",
    "cat /opt/app/.env.example": "PORT=3001\nNODE_ENV=production\nMONGODB_URI=mongodb://localhost:27017/appdb\nJWT_SECRET=your-secret-here\nLOG_LEVEL=info",
    "ls -la /opt/app": "total 48\ndrwxr-xr-x 5 app  app  4096 Jan 15 09:00 .\ndrwxr-xr-x 8 root root 4096 Jan 10 14:32 ..\n-rw-r--r-- 1 app  app   127 Jan 15 11:28 .env.example\ndrwxr-xr-x 3 app  app  4096 Jan 15 09:00 config\ndrwxr-xr-x 2 app  app  4096 Jan 15 09:00 logs\ndrwxr-xr-x 2 app  app  4096 Jan 15 09:00 node_modules\n-rw-r--r-- 1 app  app  1204 Jan 15 09:00 server.js",
    "ls -la /opt/app/.env": "ls: cannot access '/opt/app/.env': No such file or directory",
    "cat /opt/app/.env": "cat: /opt/app/.env: No such file or directory",
    "cp /opt/app/.env.example /opt/app/.env": "",
    "nano /opt/app/.env": "[Simulated editor: file contains content from .env.example]\n[Editor exited — changes saved]",
    "vim /opt/app/.env": "[Simulated editor: file contains content from .env.example]\n[Editor exited — changes saved]",
    "vi /opt/app/.env": "[Simulated editor: file contains content from .env.example]\n[Editor exited — changes saved]",
    "ls /etc/nginx/": "conf.d/  fastcgi_params  mime.types  nginx.conf  sites-available/  sites-enabled/  snippets/",
    "tail -f /var/log/nginx/error.log": "2024/01/15 11:31:50 [error] 1235#1235: *892 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.5, server: app.company.com, request: \"GET / HTTP/1.1\", upstream: \"http://127.0.0.1:3001/\", host: \"app.company.com\"",
    "cat /var/log/nginx/error.log": "2024/01/15 11:31:50 [error] 1235#1235: *892 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.5, server: app.company.com, request: \"GET / HTTP/1.1\", upstream: \"http://127.0.0.1:3001/\", host: \"app.company.com\"",
    "ps aux": "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\nroot         1  0.0  0.0  17952  1540 ?        Ss   09:00   0:00 /sbin/init\nnginx     1234  0.0  0.1  55296  4096 ?        Ss   09:23   0:01 nginx: master process\nnginx     1235  0.0  0.1  55568  3072 ?        S    09:23   0:00 nginx: worker process",
    "help": "Available commands include: ls, cat, curl, systemctl, journalctl, nginx, ps, tail, grep, cp, mv, nano, vim, df, du, id, whoami, pwd, echo",
    "?": "Available commands include: ls, cat, curl, systemctl, journalctl, nginx, ps, tail, grep, cp, mv, nano, vim, df, du, id, whoami, pwd, echo",
    "whoami": "deploy",
    "pwd": "/home/deploy"
  }
};
